apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpc-server
  template:
    metadata:
      labels:
        app: rpc-server
    spec:
      containers:
      - name: rpc-server
        image: chandavid01/assignment_demo_2023-rpc-server:latest
        ports:
        - containerPort: 8888
        env:
        - name: REDIS_ADDRESS
          value: redis-master:6379
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: rpc-server
spec:
  selector:
    app: rpc-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
